openapi: 3.1.0
info:
  title: 'Dealer Network Management - call'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: call
    description: 'Управление журналом звонков'
paths:
  /call:
    get:
      tags:
        - call
      summary: 'Получение списка звонков'
      description: 'Получение списка звонков'
      parameters:
        -
          name: src
          in: query
          description: 'Кто звонил'
          schema:
            type: string
        -
          name: dest
          in: query
          description: 'Кому звонили'
          schema:
            type: string
      responses:
        200:
          description: 'Возвращает список звонков'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Call'
        401:
          description: 'Необходима авторизация'
          content: {  }
    post:
      tags:
        - call
      summary: 'Добавление нового звонка в журнал звонков'
      description: 'Добавление нового звонка в журнал звонков'
      requestBody:
        description: 'Объект Звонок'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Call'
        required: true
      responses:
        201:
          description: 'Звонок успешно добавлен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: {  }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/call/{id}':
    get:
      tags:
        - call
      summary: 'Получение звонка по id'
      description: 'Получение звонка по id'
      parameters:
        -
          name: id
          in: path
          description: 'id звонка'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает звонок по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - call
      summary: 'Изменение звонка по ID'
      description: 'Изменение звонка по ID'
      parameters:
        -
          name: id
          in: path
          description: 'id звонка'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель Звонок'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Call'
        required: false
      responses:
        200:
          description: 'Звонок успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
