openapi: 3.1.0
info:
  title: 'Dealer Network Management - common-client'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: common-client
    description: 'Справочники клиентов дистрибьютора'
paths:
  /common-client:
    get:
      tags:
        - common-client
      summary: 'Получение списка клиентов дистрибьютора'
      description: 'Получение списка клиентов дистрибьютора'
      parameters:
        - name: id
          in: query
          schema:
            type: integer
        - name: type
          in: query
          description: "Тип клиента * `1` - Физическое лицо * `2` - Юридическое лицо\n"
          schema:
            type: integer
            enum:
              - 1
              - 2
        - name: tagId
          in: query
          description: 'Id тегов'
          schema:
            type: integer
        - name: email
          in: query
          description: Email
          schema:
            type: string
        - name: phone
          in: query
          description: 'Номер телефона'
          schema:
            type: string
        - name: first_name
          in: query
          description: 'Имя клиента'
          schema:
            type: string
        - name: middle_name
          in: query
          description: 'Отчество клиента'
          schema:
            type: string
        - name: last_name
          in: query
          description: 'Фамилия клиента'
          schema:
            type: string
        - name: company_name
          in: query
          description: 'Название компании'
          schema:
            type: string
        - name: address
          in: query
          description: Адрес
          schema:
            type: string
        - name: sex
          in: query
          description: Пол
          schema:
            type: integer
        - name: brandId
          in: query
          description: 'ID Бренда автомобиля клиента'
          schema:
            type: integer
        - name: modelId
          in: query
          description: 'ID Модели автомобиля клиента'
          schema:
            type: integer
        - name: dealerId
          in: query
          description: 'ID Дилера клиента'
          schema:
            type: integer
        - name: google_id
          in: query
          description: 'Google ID'
          schema:
            type: string
        - name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
        - name: expand
          in: query
          description: "Получение дополнительных полей, можно передать несколько значений через запятую:\n* commonClientIdentifiers - Идентификаторы клиента в Internet\n* dealers - Список дилеров по данному клиенту\n* warehouseVehicle - Список автомобилей\n"
          schema:
            type: string
        - name: createdFrom
          in: query
          description: 'Дата создания с, в формате dd.MM.yyyy'
          schema:
            type: string
        - name: createdTo
          in: query
          description: 'Дата создания по, в формате dd.MM.yyyy'
          schema:
            type: string
        - name: updatedFrom
          in: query
          description: 'Дата изменения с, в формате dd.MM.yyyy'
          schema:
            type: string
        - name: updatedTo
          in: query
          description: 'Дата изменения по, в формате dd.MM.yyyy'
          schema:
            type: string
        - name: clientId
          in: query
          description: 'ID клиента дилера'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список клиентов дистрибьютора'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommonClient'
        401:
          description: 'Необходима авторизация'
          content: { }
    post:
      tags:
        - common-client
      summary: 'Добавление клиента дистрибьютора'
      description: 'Добавление клиента дистрибьютора'
      requestBody:
        description: 'Объект CommonClient'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommonClient'
        required: true
      responses:
        200:
          description: 'Новый клиент успешно создан'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonClient'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/common-client-identificator/{type}/{value}':
    delete:
      tags:
        - common-client
      summary: 'Удаление идентификатора клиента дистрибьютора'
      description: 'Удаление идентификатора клиента дистрибьютора по типу и значению'
      parameters:
        - name: type
          in: path
          description: "Тип идентификатора клиента. Возможные значения:\n  - 1 — Google ID\n  - 2 — Yandex ID\n  - 3 — Git ID\n  - 4 — GWM ID (если применимо)\n  - 5 — Номер заказа в личном кабинете\n  - 6 — Серийный номер оплаты\n  - 7 — Ссылка на профиль Telegram\n  - 8 — Ссылка на профиль ВКонтакте\n  - 9 — Ссылка на профиль Одноклассники\n"
          required: true
          schema:
            type: string
        - name: value
          in: path
          description: 'Значение идентификатора'
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Идентификатор клиента дистрибьютора успешно удалён'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Идентификатор успешно удалён'
        400:
          description: 'Ошибка клиента'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  '/common-client/{id}':
    get:
      tags:
        - common-client
      summary: 'Получение клиента дистрибьютора по ID'
      description: 'Получение клиента дистрибьютора по ID'
      parameters:
        - name: id
          in: path
          description: 'id клиента дистрибьютора'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает клиента дистрибьютора по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonClient'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - common-client
      summary: 'Изменение клиента дистрибьютора'
      description: 'Изменение клиента дистрибьютора'
      parameters:
        - name: id
          in: path
          description: 'id клиента дистрибьютора'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель Клиент дистрибьютора'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommonClient'
        required: false
      responses:
        200:
          description: 'Клиент дистрибьютора успешно изменена'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonClient'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  '/common-client/{id}/subscribe-change':
    put:
      tags:
        - common-client
      summary: 'Изменение подписок клиента дистрибьютора'
      description: 'Изменение подписок клиента дистрибьютора'
      parameters:
        - name: id
          in: path
          description: 'ID клиента дистрибьютора'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                subscribes:
                  type: array
                  description: 'ID подписок'
                  items:
                    type: integer
      responses:
        200:
          description: 'Подписки клиента дистрибьютора успешно изменены'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscribeForm'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
