openapi: 3.1.0
info:
  title: 'Dealer Network Management - factoring-status'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: factoring-status
    description: 'Статус факторинга'
paths:
  /bankGuarantee/factoring-status:
    post:
      tags:
        - factoring-status
      summary: 'Добавление статуса факторинга'
      description: 'Добавление статуса факторинга'
      requestBody:
        description: 'Объект FactoringStatus'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FactoringStatus'
        required: true
      responses:
        201:
          description: 'Информация о статусе успешно добавлена'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FactoringStatus'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
