openapi: 3.1.0
info:
  title: 'Dealer Network Management - incadea'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: incadea
    description: Incadea
paths:
  /incadea:
    get:
      tags:
        - incadea
      summary: 'Получение истории изменений автомобилей на складе'
      description: 'Получение истории изменений автомобилей на складе'
      parameters:
        -
          name: vehicle_receipt_date_changed
          in: query
          description: 'Дата прихода на склад изменена (0 - Нет, 1 - Да)'
          schema:
            type: integer
        -
          name: updated_since
          in: query
          description: 'Дата изменения в формате ГГГГ-ММ-ДД ЧЧ:ММ:СС'
          schema:
            type: string
        -
          name: updated_till
          in: query
          description: 'Дата изменения в формате ГГГГ-ММ-ДД ЧЧ:ММ:СС'
          schema:
            type: string
        -
          name: status
          in: query
          description: 'Статус(active - Новая, deleted - Удалена, error - Ошибка, progress - В процессе, all - Все)'
          schema:
            type: string
            default: active
        -
          name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список изменений'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Incadea'
        401:
          description: 'Необходима авторизация'
          content: {  }
  '/incadea/{id}':
    put:
      tags:
        - incadea
      summary: 'Изменение записи об изменении автомобиля по ID'
      description: 'Изменение записи об изменении автомобиля по ID'
      parameters:
        -
          name: id
          in: path
          description: id
          required: true
          schema:
            type: integer
      requestBody:
        description: модель
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Incadea'
        required: false
      responses:
        200:
          description: 'Успешное изменение по ID'
          content: {  }
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    delete:
      tags:
        - incadea
      summary: 'Удаление записи об изменении автомобиля по ID'
      description: 'Удаление записи об изменении автомобиля по ID'
      parameters:
        -
          name: id
          in: path
          description: id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: 'Успешное удаление по ID'
          content: {  }
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
