openapi: 3.1.0
info:
  title: 'Dealer Network Management - nearest-contact'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: nearest-contact
    description: 'Управление следующими контактами'
paths:
  /nearest-contact:
    get:
      tags:
        - nearest-contact
      summary: 'Получение списка следующих контактов'
      description: 'Получение списка следующих контактов'
      parameters:
        -
          name: code
          in: query
          description: 'внешний идентификатор'
          schema:
            type: string
        -
          name: created_from
          in: query
          description: 'минимальное время создания в формате dd.MM.yyyy HH:mm:ss'
          schema:
            type: string
        -
          name: created_to
          in: query
          description: 'максимальное время создания в формате dd.MM.yyyy HH:mm:ss'
          schema:
            type: string
        -
          name: updated_from
          in: query
          description: 'минимальное время обновления в формате dd.MM.yyyy HH:mm:ss'
          schema:
            type: string
        -
          name: updated_to
          in: query
          description: 'максимальное время обновления в формате dd.MM.yyyy HH:mm:ss'
          schema:
            type: string
        -
          name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список следующих контактов'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NearestContact'
        401:
          description: 'Необходима авторизация'
          content: {  }
    post:
      tags:
        - nearest-contact
      summary: 'Создание следующего контакта'
      description: 'Создание следующего контакта'
      requestBody:
        description: 'Объект Следующий контакт'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NearestContact'
        required: true
      responses:
        201:
          description: 'Следующий контакт успешно создан'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NearestContact'
        400:
          description: 'Некорректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: {  }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/nearest-contact/{id}':
    get:
      tags:
        - nearest-contact
      summary: 'Получение по ID'
      description: 'Получение по ID'
      parameters:
        -
          name: id
          in: path
          description: 'id следующего контакта'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает контакт по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NearestContact'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - nearest-contact
      summary: 'Изменение контакта'
      description: 'Изменение контакта'
      parameters:
        -
          name: id
          in: path
          description: 'id контакта'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель следующий контакт'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NearestContact'
        required: false
      responses:
        200:
          description: 'Контакт успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NearestContact'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
