openapi: 3.1.0
info:
  title: 'Dealer Network Management - sale-additional-service-price'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: sale-additional-service-price
    description: 'Управление стоимостью дополнительных услуг'
paths:
  /sale-additional-service-price:
    get:
      tags:
        - sale-additional-service-price
      summary: 'Получение списка групп стоимостей дополнительных услуг'
      description: 'Получение списка групп стоимостей дополнительных услуг'
      parameters:
        - name: id
          in: query
          description: 'ID группы'
          schema:
            type: integer
        - name: serviceId
          in: query
          description: 'ID услуги'
          schema:
            type: integer
        - name: brandId
          in: query
          description: 'ID бренда'
          schema:
            type: integer
        - name: modelId
          in: query
          description: 'ID модели'
          schema:
            type: integer
        - name: status
          in: query
          description: 'Статус группы (1 - Активный, 2 - Удалено). По умолчанию только активные.'
          schema:
            type: integer
        - name: startDate
          in: query
          description: 'Дата начала действия стоимости, формат DD.MM.YYYY'
          schema:
            type: string
        - name: endDate
          in: query
          description: 'Дата окончания действия стоимости, формат DD.MM.YYYY'
          schema:
            type: string
        - name: expand
          in: query
          description: "Получение дополнительных полей, можно передать несколько значений через запятую\n* pricesNamed - список стоимостей по автомобилю с названиями параметров авто вместо их ID"
          schema:
            type: string
        - name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список групп стоимостей дополнительных услуг'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaleAdditionalServicePriceGroup'
        401:
          description: 'Необходима авторизация'
          content: { }
  '/sale-additional-service-price/{id}':
    get:
      tags:
        - sale-additional-service-price
      summary: 'Получение группы стоимостей дополнительной услуги по ID'
      description: 'Получение группы стоимостей дополнительной услуги по ID'
      parameters:
        - name: id
          in: path
          description: 'ID группы'
          required: true
          schema:
            type: integer
        - name: expand
          in: query
          description: "Получение дополнительных полей, можно передать несколько значений через запятую\n* pricesNamed - список стоимостей по автомобилю с названиями параметров авто вместо их ID"
          schema:
            type: string
      responses:
        200:
          description: 'Возвращает группу стоимостей дополнительной услуги по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleAdditionalServicePriceGroup'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
