openapi: 3.1.0
info:
  title: 'Dealer Network Management - serie'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: serie
    description: 'Управление сериями'
paths:
  /serie:
    get:
      tags:
        - serie
      summary: 'Получение списка серий'
      description: 'Получение списка серий'
      parameters:
        - name: generation_id
          in: query
          description: 'ID поколения'
          schema:
            type: integer
        - name: is_recent
          in: query
          description: 'признак активности серии 1 - только серии которые выпускаются (по умолчанию), 0 - серии, которые не выпускаются, пустое значение - все серии'
          schema:
            type: integer
        - name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список серий'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
        401:
          description: 'Необходима авторизация'
          content: { }
  '/serie/{id}':
    get:
      tags:
        - serie
      summary: 'Получение серии по ID'
      description: 'Получение серии по ID'
      parameters:
        - name: id
          in: path
          description: 'id модели'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает серию по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
