openapi: 3.1.0
info:
  title: 'Dealer Network Management - source'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: source
    description: 'Управление источниками'
paths:
  /source:
    get:
      tags:
        - source
      summary: 'Получение списка источников'
      description: 'Получение списка источников'
      parameters:
        - name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
        - name: parent_id
          in: query
          description: 'ID родительского источника'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список источников'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Source'
        401:
          description: 'Необходима авторизация'
          content: { }
