openapi: 3.1.0
info:
  title: 'Dealer Network Management - spare-warehouse-transaction'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: spare-warehouse-transaction
    description: 'Управление историей движения запчастей дилера'
paths:
  /spare-warehouse/transaction:
    get:
      tags:
        - spare-warehouse-transaction
      summary: 'Получение списка движения запчастей дилера'
      description: 'Получение списка движения запчастей дилера'
      parameters:
        - name: status
          in: query
          schema:
            type: integer
        - name: fromAt
          in: query
          description: 'С в формате dd.MM.yyyy HH:mm'
          schema:
            type: string
        - name: toAt
          in: query
          description: 'ПО в формате dd.MM.yyyy HH:mm'
          schema:
            type: string
        - name: spareCode
          in: query
          description: 'Артикул запчасти'
          schema:
            type: string
        - name: code
          in: query
          description: 'Код во внешней системе'
          schema:
            type: string
        - name: spare_id
          in: query
          schema:
            type: integer
        - name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
        - name: expand
          in: query
          description: 'Получение дополнительных полей, можно передать несколько значений через запятую spare - Запчасть дилера'
          schema:
            type: string
      responses:
        200:
          description: 'Возвращает список движений запчастей'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpareWarehouseTransaction'
        401:
          description: 'Необходима авторизация'
          content: { }
    post:
      tags:
        - spare-warehouse-transaction
      summary: 'Добавление новой записи движения запчасти'
      description: 'Добавление новой записи движения запчасти'
      requestBody:
        description: Объект
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpareWarehouseTransaction'
        required: true
      responses:
        201:
          description: 'Новая запчасть успешно создана'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpareWarehouseTransaction'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/spare-warehouse/transaction/{id}':
    get:
      tags:
        - spare-warehouse-transaction
      summary: 'Получение движения запчасти по ID'
      description: 'Получение движения запчасти по ID'
      parameters:
        - name: id
          in: path
          description: 'id движения'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает движение по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpareWarehouseTransaction'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - spare-warehouse-transaction
      summary: 'Изменение движения запчасти по ID'
      description: 'Изменение движения запчасти по ID'
      parameters:
        - name: id
          in: path
          description: 'id движения'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель Движения запчасти'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpareWarehouseTransaction'
        required: false
      responses:
        200:
          description: 'Запчасть успешно изменена'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpareWarehouseTransaction'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
