openapi: 3.1.0
info:
  title: 'Dealer Network Management - spare-warehouse-partner'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: spare-warehouse-partner
    description: 'Управление списком контрагентов'
paths:
  /spare-warehouse/partner:
    get:
      tags:
        - spare-warehouse-partner
      summary: 'Получение списка'
      description: 'Получение списка'
      parameters:
        - name: status
          in: query
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpareWarehousePartner'
        401:
          description: 'Необходима авторизация'
          content: { }
    post:
      tags:
        - spare-warehouse-partner
      summary: 'Добавление новой записи'
      description: 'Добавление новой записи'
      requestBody:
        description: Объект
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpareWarehousePartner'
        required: true
      responses:
        201:
          description: 'Новая запись успешно создана'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpareWarehousePartner'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/spare-warehouse/partner/{id}':
    get:
      tags:
        - spare-warehouse-partner
      summary: 'Получение контрагента'
      description: 'Получение контрагента'
      parameters:
        - name: id
          in: path
          description: 'id контрагента'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает контрагента'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpareWarehousePartner'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - spare-warehouse-partner
      summary: 'Изменение контрагента'
      description: 'Изменение контрагента'
      parameters:
        - name: id
          in: path
          description: 'id движения'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель контрагента'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpareWarehousePartner'
        required: false
      responses:
        200:
          description: 'Контрагент успешно изменена'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpareWarehousePartner'
        401:
          description: 'Необходима авторизация'
          content: { }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
