openapi: 3.1.0
info:
  title: 'Dealer Network Management - spare-sale'
  version: '1.0'
servers:
  - url: /api
security:
  - basicAuth: { }
  - bearerAuth: { }
tags:
  - name: spare-sale
    description: 'Документы реализации запасных частей'
paths:
  /spare-sale:
    get:
      tags:
        - spare-sale
      summary: 'Получение списка документов реализации запасных частей'
      description: 'Получение списка документов реализации запасных частей'
      parameters:
        - name: date_from
          in: query
          description: 'Дата накладной с (формат: ДД.ММ.ГГГГ)'
          schema:
            type: string
        - name: date_to
          in: query
          description: 'Дата накладной по (формат: ДД.ММ.ГГГГ)'
          schema:
            type: string
        - name: date_create_from
          in: query
          description: 'Дата создания с (формат: ДД.ММ.ГГГГ)'
          schema:
            type: string
        - name: date_create_to
          in: query
          description: 'Дата создания по (формат: ДД.ММ.ГГГГ)'
          schema:
            type: string
        - name: request_id
          in: query
          description: 'ID лида'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список калькуляций'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpareSale'
    post:
      tags:
        - spare-sale
      summary: 'Создание документа реализации запасных частей'
      description: 'Создание документа реализации запасных частей'
      requestBody:
        description: 'Объект Campaign'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpareSaleForm'
        required: true
      responses:
        200:
          description: 'Возвращает список калькуляций'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpareSaleView'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/spare-sale/{id}':
    get:
      tags:
        - spare-sale
      summary: 'Получение документа реализации запасных частей'
      description: 'Получение документа реализации запасных частей'
      parameters:
        - name: id
          in: path
          description: 'ID реализации ЗЧ'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список калькуляций'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpareSaleView'
    put:
      tags:
        - spare-sale
      summary: 'Редактирование документа реализации запасных частей'
      description: 'Редактирование документа реализации запасных частей'
      parameters:
        - name: id
          in: path
          description: 'ID реализации ЗЧ'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'Объект реализации'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpareSaleForm'
        required: true
      responses:
        200:
          description: 'Возвращает список калькуляций'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpareSaleView'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: { }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
