openapi: 3.1.0
info:
  title: 'Dealer Network Management - stage-type'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: stage-type
    description: 'Управление Типами этапов'
paths:
  /lms/stage-type:
    get:
      tags:
        - stage-type
      summary: 'Получение списка типов этапов'
      description: 'Получение списка типов этапов'
      parameters:
        -
          name: id
          in: query
          schema:
            type: integer
        -
          name: name
          in: query
          schema:
            type: string
        -
          name: code
          in: query
          schema:
            type: string
        -
          name: status
          in: query
          schema:
            type: integer
        -
          name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список типов этапов'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StageType'
        401:
          description: 'Необходима авторизация'
          content: {  }
    post:
      tags:
        - stage-type
      summary: 'Добавление нового типа этапа'
      description: 'Добавление нового типа этапа'
      requestBody:
        description: 'Объект StageType'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StageType'
        required: true
      responses:
        201:
          description: 'Новый этап успешно создан'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StageType'
        400:
          description: 'Не корректный запрос'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
        401:
          description: 'Необходима авторизация'
          content: {  }
        422:
          description: 'Ошибка в параметрах запроса'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  '/lms/stage-type/{id}':
    get:
      tags:
        - stage-type
      summary: 'Получение Типа этапа по ID'
      description: 'Получение Типа этапа по ID'
      parameters:
        -
          name: id
          in: path
          description: 'id типа этапа'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает тип этапа по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StageType'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - stage-type
      summary: 'Изменение Типа этапа'
      description: 'Изменение Типа этапа'
      parameters:
        -
          name: id
          in: path
          description: 'id типа этапа'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель Тип этапа'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StageType'
        required: false
      responses:
        200:
          description: 'Тип этапа успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StageType'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
