openapi: 3.1.0
info:
  title: 'Dealer Network Management - vehicle-additional-service'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: vehicle-additional-service
paths:
  /vehicle-additional-service:
    post:
      tags:
        - vehicle-additional-service
      summary: 'Изменение автомобиля'
      description: 'Добавление дополнительной услуги в автомобиль'
      requestBody:
        description: 'Объект «Модель для добавления дополнительной услуги к автомобилю»'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleAdditionalService'
        required: true
      responses:
        200:
          description: 'Услуга успешно добавлена'
          content: {  }
        401:
          description: 'Необходима авторизация'
          content: {  }
        422:
          description: 'Ошибка валидации данных'
          content: {  }
  '/vehicle-additional-service/{id}':
    delete:
      tags:
        - vehicle-additional-service
      summary: 'Изменение автомобиля'
      description: 'Удаление дополнительной услуги из автомобиля'
      parameters:
        -
          name: id
          in: path
          description: 'id доп. услуги автомобиля'
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Услуга успешно удалена'
          content: {  }
        401:
          description: 'Необходима авторизация'
          content: {  }
        422:
          description: 'Ошибка валидации данных'
          content: {  }
  '/vehicle-additional-service/{vin}':
    get:
      tags:
        - vehicle-additional-service
      summary: 'Получение списка дополнительных услуг'
      description: 'Получение списка дополнительных услуг  автомобиля'
      parameters:
        -
          name: vin
          in: path
          description: 'VIN автомобиля'
          required: true
          schema:
            type: string
        -
          name: status
          in: query
          description: 'Статус. 1 - Активна, 2 - Удалена, 3 - Неактивна'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список дополнительных услуг'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleAdditionalService'
        401:
          description: 'Необходима авторизация'
          content: {  }
        422:
          description: 'Ошибка валидации данных'
          content: {  }
