openapi: 3.1.0
info:
  title: 'Dealer Network Management - warehouse-vehicle-used'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: warehouse-vehicle-used
    description: 'Управление автомобилями с пробегом'
paths:
  /warehouse/vehicle-used/yearly-sales:
    get:
      tags:
        - warehouse-vehicle-used
      summary: 'Получение списка автомобилей с пробегом, сгруппированного по дилеру и по году'
      description: 'Получение списка автомобилей с пробегом, сгруппированного по дилеру и по году'
      parameters:
        -
          name: dealer_code
          in: query
          description: 'Код дилера'
          schema:
            type: string
        -
          name: sale_year
          in: query
          description: Год
          schema:
            type: string
        -
          name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список автомобилей с пробегом, сгруппированного по дилеру и по году'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehouseVehicleUsedYearlySales'
        401:
          description: 'Необходима авторизация'
          content: {  }
