openapi: 3.1.0
info:
  title: 'Dealer Network Management - warehouse-public-vehicle'
  version: '1.0'
servers:
  -
    url: /api
security:
  -
    basicAuth: {  }
  -
    bearerAuth: {  }
tags:
  -
    name: warehouse-public-vehicle
    description: 'Управление автомобилями'
paths:
  /warehouse-public/vehicle:
    get:
      tags:
        - warehouse-public-vehicle
      summary: 'Получение списка автомобилей'
      description: 'Получение списка автомобилей'
      parameters:
        -
          name: brand_id
          in: query
          description: 'ID бренда'
          schema:
            type: integer
        -
          name: model_id
          in: query
          description: 'ID модели'
          schema:
            type: integer
        -
          name: model_code
          in: query
          description: 'Код модели'
          schema:
            type: string
        -
          name: conditional_sale
          in: query
          description: 'Условно реализован (0 - Нет, 1 - Да, 2 - Был усл. реализован)'
          schema:
            type: integer
        -
          name: page
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
        -
          name: expand
          in: query
          description: "Список связанных сущностей. Например:\nphotos.upload - для включения в результат фотографий автомобиля;\nprograms - добавить в ответ список программ верификации автомобиля;\nwarranty - данные по гарантийному сроку автомобиля;\ncolor - для получения данных по цвету кузова;\ntrim - для получения данных по цвету обивки;\ntags - получение списка тегов;\nvideos - получение списка видео;\nvehicleDiscounts - получения списка мотивационных программ для автомобиля;\nmaxCompensationDiscountsSum - сумма максимально возможной компенсационной скидки;\nroutePoints - получение списка точек маршрута автомобиля;\noptionsExtendedChangan - получение списка характеристик для Changan;\nvehiclePrices — цены прайс-листов\n"
          schema:
            type: string
        -
          name: dealer_code
          in: query
          description: 'Код дилера'
          schema:
            type: string
        -
          name: dealer_contractor_code
          in: query
          description: 'Код контрагента дилера'
          schema:
            type: string
        -
          name: holding_code
          in: query
          description: 'Код холдинга'
          schema:
            type: string
        -
          name: is_archive
          in: query
          description: 'В архиве'
          schema:
            type: integer
        -
          name: status_code
          in: query
          description: 'Код статуса'
          schema:
            type: string
        -
          name: vehicle_is_sold
          in: query
          description: Продана
          schema:
            type: integer
        -
          name: is_trade_in
          in: query
          description: Б\У
          schema:
            type: integer
        -
          name: vehicle_vin
          in: query
          description: 'VIN номер автомобиля'
          schema:
            $ref: '#/components/schemas/WarehouseVehicle/properties/vehicle_vin'
        -
          name: vehicle_is_in_stock
          in: query
          description: 'Автомобиль находится на складе дилера'
          schema:
            type: integer
        -
          name: withoutDealerCode
          in: query
          description: 'Без кода дилера'
          schema:
            type: integer
        -
          name: verificationProgramId
          in: query
          description: 'ID программы проверки автомобиля'
          schema:
            type: integer
        -
          name: createdFrom
          in: query
          description: 'Дата создания с, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: createdTo
          in: query
          description: 'Дата создания по, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: paymentDateFrom
          in: query
          description: 'Дата оплаты авто дилером с, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: paymentDateTo
          in: query
          description: 'Дата оплаты авто дилером по, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: internal_status_id
          in: query
          description: 'Внутренний статус автомобиля (см. warehouse-public-vehicle-internal-status)'
          schema:
            type: integer
        -
          name: vehicle_code
          in: query
          description: 'Код автомобиля'
          schema:
            type: string
        -
          name: hasPts
          in: query
          description: 'Наличие номера ПТС у автомобиля 1 - есть, 0 - нет'
          schema:
            type: integer
        -
          name: hasEpts
          in: query
          description: 'Наличие файла E-ПТС у автомобиля 1 - есть, 0 - нет'
          schema:
            type: integer
        -
          name: curb_weight
          in: query
          description: 'Масса ТС в снаряженном состоянии'
          schema:
            type: integer
        -
          name: shipping_order_number
          in: query
          description: 'Номер заявки на доставку'
          schema:
            type: string
        -
          name: vehicle_order_no
          in: query
          description: 'Номер заказа'
          schema:
            type: string
        -
          name: saledFrom
          in: query
          description: 'Дата продажи с, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: saledTo
          in: query
          description: 'Дата продажи по, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: vehicleReceiptDateFrom
          in: query
          description: 'Дата прихода на склад с, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: vehicleReceiptDateTo
          in: query
          description: 'Дата прихода на склад по, в формате dd.MM.yyyy'
          schema:
            type: string
        -
          name: country_id
          in: query
          description: 'Id страны связанного дилера'
          schema:
            type: string
        -
          name: 'dealersWithTags[]'
          in: query
          description: 'Дилер с тегами - список id тегов дилеров, чьи машины надо получить'
          schema:
            type: array
        -
          name: 'dealersWithoutTags[]'
          in: query
          description: 'Исключить дилеров с тегами - список тегов дилеров, чьи машины надо отсечь'
          schema:
            type: array
        -
          name: 'withTags[]'
          in: query
          description: 'Авто с тегами - список id тегов автомобилей, чьи машины надо получить'
          schema:
            type: array
        -
          name: withTagsLogic
          in: query
          description: 'Способ соединения тегов и/или'
          schema:
            type: string
            default: or
            enum:
              - and
              - or
        -
          name: 'withoutTags[]'
          in: query
          description: 'Исключить авто с тегами - список id тегов автомобилей, которые нужно исключить'
          schema:
            type: array
        -
          name: withoutTagsLogic
          in: query
          description: 'Способ соединения тегов и/или'
          schema:
            type: string
            default: or
            enum:
              - and
              - or
        -
          name: sort
          in: query
          description: "Параметр по которому идет сортировки, например: \"sort=-vehicle_dealer_payment_at\" - сортировка Я-а по дате покупки авто, \"sort=vehicle_dealer_payment_at\" - сортировка А-я по дате покупки авто\n"
          schema:
            type: string
        -
          name: is_free_stock
          in: query
          description: 'Свободный склад - 1 - готов, 0 - нет'
          schema:
            type: integer
        -
          name: factoring_status
          in: query
          description: 'Статус факторинга'
          schema:
            type: integer
      responses:
        200:
          description: 'Возвращает список автомобилей'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
  /warehouse-public/vehicle/dealer-discount:
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Изменение скидки от дилера'
      description: 'Изменение скидки от дилера'
      parameters:
        -
          name: id
          in: query
          description: 'id авто'
          schema:
            type: integer
        -
          name: vin
          in: query
          description: 'vin авто'
          required: true
          schema:
            type: string
      requestBody:
        description: 'Форма изменения скидки от дилера'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleDealerDiscountForm'
        required: false
      responses:
        200:
          description: 'Автомобиль успешно сохранён'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  /warehouse-public/vehicle/optional-equipment:
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Управление дополнительным оборудованием'
      description: 'Управление дополнительным оборудованием'
      parameters:
        -
          name: id
          in: query
          description: 'id авто'
          schema:
            type: integer
        -
          name: vin
          in: query
          description: 'vin авто'
          required: true
          schema:
            type: string
      requestBody:
        description: 'Форма для резервирования автомобиля'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OptionalEquipmentForm'
        required: false
      responses:
        200:
          description: 'Дополнительно оборудование успешно сохранено'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptionalEquipmentForm'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  /warehouse-public/vehicle/publication-statuses-list:
    get:
      tags:
        - warehouse-public-vehicle
      summary: 'Получение списка статусов публикации автомобиля'
      description: 'Получение списка статусов публикации автомобиля'
      responses:
        200:
          description: 'Возвращает список статусов публикации автомобиля'
          content:
            application/json:
              schema:
                type: array
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  /warehouse-public/vehicle/reserve:
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Резервирование  автомобиля'
      description: 'Резервирование автомобиля'
      parameters:
        -
          name: vin
          in: query
          description: 'vin авто'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'Форма для резервирования автомобиля'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReserveVehicleForm'
        required: false
      responses:
        200:
          description: 'Автомобиль успешно зарезервирован'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  '/warehouse-public/vehicle/update-by-job/{job}':
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Изменение автомобиля'
      description: 'Изменение автомобиля'
      parameters:
        -
          name: job
          in: path
          description: 'JOB автомобиля'
          required: true
          schema:
            type: string
      requestBody:
        description: 'модель Автомобиль'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehousePublicVehicle'
        required: false
      responses:
        200:
          description: 'Автомобиль успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  '/warehouse-public/vehicle/update-by-vin/{vin}':
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Изменение автомобиля'
      description: 'Изменение автомобиля'
      parameters:
        -
          name: vin
          in: path
          description: 'VIN автомобиля'
          required: true
          schema:
            type: string
      requestBody:
        description: 'модель Автомобиль'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehousePublicVehicle'
        required: false
      responses:
        200:
          description: 'Автомобиль успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  '/warehouse-public/vehicle/update-sale-at/{id}':
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Изменение даты продажи  автомобиля'
      description: 'Изменение даты продажи автомобиля'
      parameters:
        -
          name: id
          in: path
          description: 'ID авто'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'Форма для изменения даты продажи автомобиля'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleDealerSaleAtForm'
        required: false
      responses:
        200:
          description: 'Автомобиль успешно сохранён'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
  '/warehouse-public/vehicle/{id}':
    get:
      tags:
        - warehouse-public-vehicle
      summary: 'Получение автомобиля по ID'
      description: 'Получение автомобиля по ID'
      parameters:
        -
          name: id
          in: path
          description: 'ID автомобиля'
          required: true
          schema:
            type: integer
        -
          name: expand
          in: query
          description: 'Параметр позволяющий получить в ответе связные данные (photos, options, ptsStatus, programs, base, color, tags, trim)'
          schema:
            type: string
      responses:
        200:
          description: 'Возвращает автомобиль по ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
    put:
      tags:
        - warehouse-public-vehicle
      summary: 'Изменение автомобиля'
      description: 'Изменение автомобиля'
      parameters:
        -
          name: id
          in: path
          description: 'id пакета'
          required: true
          schema:
            type: integer
      requestBody:
        description: 'модель Автомобиль'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WarehousePublicVehicle'
        required: false
      responses:
        200:
          description: 'Автомобиль успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WarehousePublicVehicle'
        401:
          description: 'Необходима авторизация'
          content: {  }
        404:
          description: 'Объект не найден'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
