<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() === 'sqlite') {
            $this->upSqlite();

            return;
        }

        // 1. Rename tables
        Schema::rename('webhook_endpoints', 'proxy_endpoints');
        Schema::rename('webhook_requests', 'proxy_requests');

        // 2. proxy_requests: rename FK column webhook_endpoint_id → proxy_endpoint_id
        DB::statement('ALTER TABLE proxy_requests RENAME COLUMN webhook_endpoint_id TO proxy_endpoint_id');

        // 3. Drop old FK constraint (name generated by Laravel)
        DB::statement('ALTER TABLE proxy_requests DROP CONSTRAINT IF EXISTS proxy_requests_webhook_endpoint_id_foreign');
        DB::statement('ALTER TABLE proxy_requests DROP CONSTRAINT IF EXISTS webhook_requests_webhook_endpoint_id_foreign');

        // 4. proxy_requests.id: bigint → uuid
        DB::statement('ALTER TABLE proxy_requests ADD COLUMN id_new uuid DEFAULT gen_random_uuid() NOT NULL');
        DB::statement(<<<'SQL'
            DO $$
            DECLARE v_name text;
            BEGIN
                SELECT constraint_name INTO v_name
                FROM information_schema.table_constraints
                WHERE table_name = 'proxy_requests' AND constraint_type = 'PRIMARY KEY';
                IF v_name IS NOT NULL THEN
                    EXECUTE 'ALTER TABLE proxy_requests DROP CONSTRAINT ' || quote_ident(v_name);
                END IF;
            END $$
            SQL);
        DB::statement('ALTER TABLE proxy_requests DROP COLUMN id');
        DB::statement('ALTER TABLE proxy_requests RENAME COLUMN id_new TO id');
        DB::statement('ALTER TABLE proxy_requests ADD PRIMARY KEY (id)');

        // 5. Drop request_uuid (redundant — id is now UUID)
        DB::statement('ALTER TABLE proxy_requests DROP COLUMN IF EXISTS request_uuid');

        // 6. Add request and response JSON columns
        DB::statement('ALTER TABLE proxy_requests ADD COLUMN request jsonb NULL');
        DB::statement('ALTER TABLE proxy_requests ADD COLUMN response jsonb NULL');

        // 7. Re-add FK constraint
        DB::statement('ALTER TABLE proxy_requests ADD CONSTRAINT proxy_requests_proxy_endpoint_id_foreign FOREIGN KEY (proxy_endpoint_id) REFERENCES proxy_endpoints(id) ON DELETE CASCADE');
    }

    private function upSqlite(): void
    {
        // SQLite does not support DROP CONSTRAINT, gen_random_uuid(), or DO $$ blocks.
        // Since this always runs on a fresh in-memory test DB (no data), we recreate.

        DB::statement('PRAGMA foreign_keys = OFF');

        Schema::rename('webhook_endpoints', 'proxy_endpoints');
        Schema::dropIfExists('webhook_requests');

        // Recreate proxy_requests with the final schema (already applies columns
        // that _400000/_500000 would drop, and _600000 would add — so those
        // migrations are no-ops on SQLite).
        Schema::create('proxy_requests', static function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignId('proxy_endpoint_id')->constrained('proxy_endpoints')->cascadeOnDelete();
            $table->string('request_id')->unique();
            $table->string('status', 32)->default('received')->index();
            $table->json('normalized_data')->nullable();
            $table->json('request')->nullable();
            $table->json('response')->nullable();
            $table->json('message_box')->nullable();
            $table->timestamp('received_at')->nullable();
            $table->timestamp('processed_at')->nullable();
            $table->timestamps();

            $table->index('proxy_endpoint_id');
        });

        DB::statement('PRAGMA foreign_keys = ON');
    }

    public function down(): void
    {
        throw new RuntimeException('This migration cannot be reversed.');
    }
};
