http:
  routers:
    scenario:
      rule: Host(`scenario.test`)
      entryPoints:
        - web
      service: scenario

    scenario-local-ip:
      rule: PathPrefix(`/`)
      priority: 1
      entryPoints:
        - web
      service: scenario

    scenario-centrifugo:
      rule: Host(`centrifugo.scenario.test`)
      entryPoints:
        - web
      service: scenario-centrifugo

    buggregator:
      rule: Host(`buggregator.scenario.test`)
      entryPoints:
        - web
      service: buggregator

    temporal-ui:
      rule: Host(`temporal.scenario.test`)
      entryPoints:
        - web
      service: temporal-ui

  services:
    scenario:
      loadBalancer:
        servers:
          - url: http://scenario-laravel:8080

    scenario-centrifugo:
      loadBalancer:
        servers:
          - url: http://scenario-centrifugo:8000

    buggregator:
      loadBalancer:
        servers:
          - url: http://scenario-buggregator:8000

    temporal-ui:
      loadBalancer:
        servers:
          - url: http://scenario-temporal-ui:8080
